### ISSUE TITLE
Implement window

### ISSUE THREAD

**Issue by bexedmondson** [littlewoo/tgds#1]
Literally as easy as making the main class that will initialise the window that pong will play in.

**Comment by bexedmondson** [comment]
If you feel fancy, add a line in the middle to make it clear which half is which :P

**Comment by littlewoo** [comment]
Implemented a basic frame and panel setup to draw a field. Doesn't draw anything else yet, but the methods are in place to make it straightforward to add that stuff. First issue resolved :)
