### ISSUE TITLE
Refactor InputHandler

### ISSUE THREAD

**Issue by littlewoo** [littlewoo/tgds#11]
At the moment, InputHandler is a dirty hack, with lots of stuff hard coded to make pong commands work. This should be refactored, especially as it's a class which could be very reusable for other games.

**Comment by littlewoo** [comment]
My thinking on this:

So, the problem at hand is that we need to make commands to fire at the game. These commands sometimes need to know variables from the input state. For example, in Pong, the input handler knows both the player, and the direction (based on what key was pressed in the input), and the command to be passed to the game controller needs to include this data. At the moment, this is done by having the input handler strongly coupled to the general Pong interface, but it would be nice to have the input handler be able to take inputs and build commands without having to know the specifics of how the command is built. For this, I suggest an InputTypeHandler (or something) interface, which allows the InputHandler to take input and tell the InputTypeHandler to build the relevant command. Implementing classes of the InputTypeHandler, which know what input state they need, can then build the command and fire it.

**Comment by samwilson93** [comment]
This is something where it'd probably good to all be around a piece of paper and shoot ideas at each other
