### ISSUE TITLE
Implement player bat behaviour

### ISSUE THREAD

**Issue by bexedmondson** [littlewoo/tgds#2]
Add bat initialisation code to the main class, and make it so the bats respond to keyboard input at an appropriate speed, and don't go beyond the edges of the window.

**Comment by littlewoo** [comment]
I've implemented a GameFieldObject class representing items in the field of play, off the top of my head:
-paddles
-ball(s?)
-walls
-goal
I've also made a stub Paddle, though it still needs everything to be implemented.

**Comment by bexedmondson** [comment]
Filled in the Direction enum a little bit just to see if eclipse was working correctly with git, and started a VERY basic move function. Need to add values to the enum next.

**Comment by littlewoo** [comment]
Just made commits c5ef0ca and 9943470. All that's left to do now is have the UI handle player input, and paint the paddles! :+1:

**Comment by littlewoo** [comment]
So, there are still improvements which need to be made to the paddles - they don't stop at the edge of the field, and the movement speed is both arbitrary and slow, but all the input stuff is in place. The stopping at the edge of the world should be covered by the combination of collision detection (#4) and implement walls (#12). The improvements to speed and acceleration will be part of the game loop (#13). Therefore, I'm calling this done!
