### ISSUE TITLE
Implement collisions

### ISSUE THREAD

**Issue by bexedmondson** [littlewoo/tgds#4]
Add code to one of the classes (discuss!) that detects collisions between a bat and the ball, and changes the direction of the ball. To begin with, we can just reverse the left-right direction (we can make another issue for more complicated collisions once we've got a basic game going and if we have time).

**Comment by samwilson93** [comment]
I plan to do this!  As (luckily) pong is a basic 2D game, I was thinking about implementing a base class "object" that we can make all things inherit from that just has the functionality "getBounds" returning a set of points, that would be the objects boundary if it was a square. Then a function called "collidesBounds()" that accepts a set of points (the boundaries) which will tell each object is in another objects boundaries.  Unless anyone has any other ideas, I am all ears :)

**Comment by samwilson93** [comment]
Also, I will include an abstract method "bounce" which will have to be over-ridden for each class with how the object will react :)

**Comment by bexedmondson** [comment]
John has been very efficient and there's already a function that does the getBounds thing you were talking about, and I believe that it's called getShape, under the GameFieldObject class!

**Comment by samwilson93** [comment]
Omg, thank you John!  <3 I will look at that :P

**Comment by littlewoo** [comment]
Sounds like a good plan! :) I like how we're on the same wavelength... :wavy_dash: The framework I set up in #1 should fit exactly with your plan. There's a class [GameFieldObject](tgds/pong/src/com/tgds/pong/game/GameFieldObject.java) which has some of the stuff you'll need already. Also every object has a shape, which should do what you need... :+1: I like GitHub's emoticon thingies...

**Comment by samwilson93** [comment]
I should start using them:exclamation:

**Comment by littlewoo** [comment]
Good :idea: idea!

**Comment by littlewoo** [comment]
good :bulb: idea?

**Comment by bexedmondson** [comment]
Sam - considering that the only object that will react to bouncing, I'm going to put in a bounce class directly in the BallController class, or wherever is appropriate, I think, while I'm doing #12 . Is that okay? Then you will just need to detect collisions between the bats and the ball.

**Comment by samwilson93** [comment]
That sounds good!  Also as we are using the Java shape class and this collision detection I was thinking I would just place it in the GameFieldObject class?  Then have an abstract procedure "collide" or something?

**Comment by samwilson93** [comment]
Oh Bex, this isn't totally true dependant on how we're doing the walls, if they're objects then the paddles will detect collision with them to stop?

**Comment by samwilson93** [comment]
Have implemented all the background for collision detection, each class will need to react differently.  Are we going to gave them as separate tasks?

**Comment by bexedmondson** [comment]
I think i'll wait to do the walls until you're done here, Sam! Um, would you rather I did it with objects? I don't think I mind. Also, if it IS with objects then we might to have different methods depending on whether it's a collision with the wall or a paddle?

**Comment by bexedmondson** [comment]
potentially we should talk about this in person tomorrow.

**Comment by bexedmondson** [comment]
Success!
