### ISSUE TITLE
The second time you score a goal, the ball disappears and the goal isn't counted.

### ISSUE THREAD

**Issue by littlewoo** [littlewoo/tgds#51]
The second time a goal is hit by the ball, instead of triggering the goal scored routine - reset the ball to the middle and increment the score - the ball starts disappearing into the goal, and the score isn't counted. 

Most probably, some state is set in the Goal class when a goal is scored, which needs to be reset and isn't being.

To recreate:
run the game
leave it to run - the ball will score once in the right hand goal, and the second time this bug will happen.

**Comment by bexedmondson** [comment]
I FIXED IT :D Fixed on branch 51-scoring-bug. Turned out that the sound stuff had added an update function to Goal, but Goal wasn't added to the updateList  so update was never called.
