### ISSUE TITLE
Implement painting of the game

### ISSUE THREAD

**Issue by littlewoo** [littlewoo/tgds#9]
At an appropriate rate, poll the game (or repaint every time it updates, whatever works best) for its current state, and paint that onto the GamePanel.

**Comment by bexedmondson** [comment]
Have you already done this?

**Comment by littlewoo** [comment]
Mostly. I want to improve the way it's threaded though. At the moment it's hardcoded to update on its own thread every now and again. I'd like to make it so it's tied in to the game loop in some way. Or at least tidy it up so it's not all hard coded in the gamepanel.
